apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subtraction-hpa
  namespace: subtraction
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subtraction
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
