apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: bogdanserdinov/infra-example:ef0cb6f6
          command: [ "/bin/sh", "-c", "gateway" ]
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: gateway-config
          livenessProbe:
            httpGet:
              path: /heathz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
