name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install mage
        run: git clone https://github.com/magefile/mage &&
          cd mage &&
          go run bootstrap.go &&
          cd .. &&
          rm -r mage

      - name: Build
        run: mage -v services

  cd:
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push')
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # could be another images registry
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tag
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Build and push
        env:
          SHORT_SHA: ${{ env.SHORT_SHA }}
          ECR_REGISTRY: bogdanserdinov
          ECR_REPOSITORY: infra-example
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA
          
      - name: Logout of DockerHub
        run: docker logout

      - name: Update Manifests
        env:
          IMAGE_TAG: ${{ env.SHORT_SHA }}
          IMAGE_NAME: bogdanserdinov/infra-example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd deploy/k8s/deployments
          for file in $(find . -type f -name "*.yaml"); do
            sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$IMAGE_TAG|g" "$file"
          done
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update Image tag to $IMAGE_TAG"
          git push
